### ISSUE TITLE
Modify config

### ISSUE THREAD

**Issue by HPWebdeveloper** [HPWebdeveloper/laravel-pay-pocket#32]
https://github.com/HPWebdeveloper/laravel-pay-pocket/blob/28be370ec1285390fd142ced583fcc10c4a0db26/config/pay-pocket.php#L25

As the log reference is now flexible to get custom class and static methods like, `random`
I believe this 'log_reference_length' is not general and it should be 'log_reference_parmas' and the default value should be `[12]` instead of `12`

In this way we let the params to have values like this [...,...,...]

@3m1n3nc3 Can you modify this?

**Comment by 3m1n3nc3** [comment]
I remember we had it this way initially before if was removed by a pull request, let do it.

**Comment by HPWebdeveloper** [comment]
@3m1n3nc3 
Yes I see, https://github.com/HPWebdeveloper/laravel-pay-pocket/pull/16#issuecomment-1890935024

The initial approach was too complex. please make it simple.

**Comment by 3m1n3nc3** [comment]
I opened a new pull request

**Comment by HPWebdeveloper** [comment]
> I opened a new pull request

thanks

**Comment by HPWebdeveloper** [comment]
well done!
